### ISSUE TITLE
works well!

### ISSUE THREAD

**Issue by boneskull** [piffall/PXESetupWizard#11]
Hi,

After having failed to install Debian from a bootable USB stick, I started looking at network installations.  Not knowing literally anything about it, I stumbled on this project.

I was not able to get the Docker image working, since that's another layer of something-I-don't-understand.  I happened to have another Linux machine handy, and ran a manual installation.

I didn't understand that I needed to actually go download a tarball and extract it into `/srv/tftp`.  *If this was unintended, there may be a bug*.  I understand `syslinux` is a bootloader, but I don't know why it was installed.  My client machine reported a PXE error (which I failed to capture) and quit after encountering the default configuration.

Once I had extracted the tarball, things worked properly.  This tarball also wanted to overwrite `pxelinux.cfg/`, which I had to remove manually.  I believe it was complaining because `pxelinux.cfg/` was a symlink.

A couple suggestions to make things go more smoothly:

1.  Change the prompt of "Install scripts?" to be more descriptive about what's actually happening.  I answered "Yes", but didn't use the downloaded files (to my knowledge).  
2.  Add mention that a user may need to `curl -O uri://netboot.tar.gz` into `/srv/tftp` in `README.md` or script prompts.

Of course, you're not in the business of teaching PXE basics to noobs. :smile:

Anyway, thanks again. I probably couldn't have gotten this working without your effort.

**Comment by piffall** [comment]
Thank you @boneskull . I appreciate your comment, and I'll try to make it more clear to users.
