### ISSUE TITLE
unable to pxe boot debian/ubuntu via uefi

### ISSUE THREAD

**Issue by Elselei** [piffall/PXESetupWizard#13]
![image](https://user-images.githubusercontent.com/19662303/153332616-d13ae96a-87a3-4c9f-ae17-910d26601ac0.png)

**Comment by piffall** [comment]
Hi @Elselei 

By now, UEFI is not supported. It is possible, however, some limitations exists:

 * UEFI System Secure Boot option enabled is not supported.
 * Not all OSs will work.
 * DHCP settings will require changes.

If it still work for you. Please, let me know.

**Comment by Elselei** [comment]
tks
